#!/bin/bash
# This does the same as bitbucket-pipelines.yml, Download step.
# Should be auto-generated by a tool.

openICPSRID=$1

if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
if [ -d $openICPSRID ]; then \rm -rf $openICPSRID; fi
if [ -f tools/download_openicpsr-private.py ]; then python3 tools/download_openicpsr-private.py $openICPSRID; fi
mkdir cache
mv *.zip cache/
chmod a+rx ./automations/*.sh
./automations/01_prepare_aux.sh
./automations/02_list_data_files.sh $openICPSRID
./automations/03_list_program_files.sh $openICPSRID
./automations/04_create_manifest.sh $openICPSRID
ls -lR